### ISSUE TITLE
indexed events

### ISSUE THREAD

**Issue by ethers** [Giveth/vaultcontract#10]
Seems it would be helpful for some of the events to have indexed arguments.

    event PaymentAuthorized(uint idPayment, address recipient, uint amount);
    event PaymentExecuted(uint idPayment, address recipient, uint amount);
    event PaymentCanceled(uint idPayment);

If `idPayment` was indexed it would be easier to answer:
- what happened to a particular payment

If `recipient` was indexed it would be easier to answer:
- what are the payments authorized/executed for a recipient?

Worth considering whether `from` and `spender` should be indexed too.

    event EtherReceived(address from, uint amount);
    event SpenderAuthorization(address spender, bool authorized);

**Comment by jbaylina** [comment]
Absolutelly right!!

I fixed it. 

Thank you very much for the contribution.!
