### ISSUE TITLE
Payment Struct restructuring

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontract#13]
Payment Struct change description to name and add an identityHash so that it is easy to connect the payments in the milestone tracker to the payments in the vault

 struct Payment {
        string **name**;     // What is the purpose of this payment
        address spender;        // Who is sending the funds
        **bytes32 identityHash** //Unique identifier to connect payments
        uint earliestPayTime;   // The earliest a payment can be made (Unix Time)
        bool canceled;         // If True then the payment has been canceled
        bool paid;              // If True then the payment has been paid
        address recipient;      // Who is receiving the funds
        uint amount;            // The amount of wei sent in the payment
        uint securityGuardDelay;// The seconds `securityGuard` can delay payment
    }

This Identity hash will also need to be added to the milestone struct in the Milestone tracker and it will need to be the same so that it connects the two inputs 

Credit for this idea goes to the infamous vojtech ;-) but before attacking we should wait for vojtech to nail down his awesome flow diagrams for the process here.

**Comment by jbaylina** [comment]
Done!
