### ISSUE TITLE
Random Tokens sent to a vault are lost forever

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontract#32]
If someone randomly sends REP tokens to a Vault, I would like a function that would allow us to remove it, and also would be able to remove ETH in the instance it is sent to a vault that is only meant to hold some token. 

I think the `escapeHatch()` is the right function for this... if we just add a parameter to the `escapeHatch()` that allows the `escapeHatchCaller` to choose the token to remove, we would be good.

**Comment by jbaylina** [comment]
Implemented in develop.
