### ISSUE TITLE
The Vault is designed only for ETH at this stage

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontract#5]
Sooner rather than later we will want to add token functionality to a vault... maybe it is a second modified version of this contract...

**Comment by jbaylina** [comment]
Absolutely!! I'll add this functionality!

**Comment by jbaylina** [comment]
See this PR https://github.com/Giveth/vaultcontract/pull/7

**Comment by GriffGreen** [comment]
:-D The Escapable contract declares the base token... see the develop branch :-D

**Comment by jbaylina** [comment]
Done in the develop branch
