### ISSUE TITLE
Vault changes and a general report from testnet testing

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontract#8]
Vault changes:
 executePayment = collectMilestonePayment 

Lessons from testing:

1. Multisig requires you confirm the tx
2. vault needs to change to vault.address on the js helper file
3. accept proposed milestone sha3
4. lots of gas limit issues, 8 milestones worked... we should probably only recommend 6 milestones per milestone tracker contract
5.  execute payment should be collect milestone payment

**Comment by jbaylina** [comment]
This Vault is not only for milestones, so it should not include the word `Milestone`

1. -> This is a problem of the multisig.
2. -> This is in the MVP when milestones are deployed
3. -> The SHA is to prevent the race condition.
4. -> Yes! This should be explained in the README / In the code comments
5. -> Again. This contract is not only intended by the milestoneTracker contract. It can be used also for a regular payment for example.
