### ISSUE TITLE
SafeMath for earliestPayTime... and everything else

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/vaultcontract#9]
We might consider Zeppelin's safe math contract… safe add and safe multiply and all that...

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/SafeMath.sol

The only line that i really worry about is earliestPayTime… because approvedSpenders could maybe make an overflow/underflow with some weird numbers when they add a delay time to the vault... Which could lead to unpredictable outcomes

**Comment by jbaylina** [comment]
Just fixed the possible overflow in the earlyPayTime calculation.
